datacsv = readtable('/home/roberto/Documents/Dr. Fisiologia/Jogo do Goleiro/MatlabScripts/Git/data_files/response_time_analysis/set2.csv');
raw_data = datacsv{:,:};

% compatibilization

data = [1*ones(size(raw_data,1),1)  1*ones(size(raw_data,1),1) ...
    raw_data(:,5) 1*ones(size(raw_data,1),1) ...
    raw_data(:,6)  raw_data(:,4) ...
    raw_data(:,3) raw_data(:,2) ...
    raw_data(:,1)];